### PR TITLE
Document junit reporter options

### PR DESCRIPTION
**Pull request by marcin-wosinek**

### CODE REVIEW

**Comment by bloveridge** [comment]
I'm uncomfortable with this for a few reasons.

1. The heading is simply "Options" when these are JUnitXmlReporter-specific options; not all reporters have the same options. The example above the addition is a JUnitXmlReporter example, but it could as easily be an example with a different reporter.
2. The documentation is incomplete. You only cover `consolidateAll` and `filePrefix`. If you're going to pick only a few, it would seem better if they matched the example they are preceded by.
3. The documentation is wrong. This copy states "By default all spec files produce different outputs" but that is not true in the 2.x version which this pull request targets; `consolidateAll` is default `true`.
4. The documentation in the source file is more complete and more likely to be kept up to date.

All things considered, I would prefer a link to the appropriate lines in the source file, something like:

For more options, view the [JUnitXmlReporter source](https://github.com/larrymyers/jasmine-reporters/blob/master/src/junit_reporter.js#L55-L82).

**Comment by marcin-wosinek** [comment]
Oh, I completely missed the jsdoc in the file. Is it built somewhere, so instead of my changes we could put a link for different reporters configurations?

**Comment by bloveridge** [comment]
The code is not built anywhere, nor are there any Github Pages for it set up. For now the best thing to do would simply be a link to the various source files in the Github repo.

**Comment by bloveridge** [comment]
No action in almost 3 months; closing.

**Pull request closed without merging**
