### PR TITLE
Sonar generic reporter

### PR DESCRIPTION
**Pull request by PloughingAByteField**
Add support for sonar source generic coverage http://docs.sonarqube.org/display/PLUG/Generic+Test+Coverage so tests are picked up

### CODE REVIEW

**Comment by PloughingAByteField** [comment]
This is to allow protractor tests be picked by sonar

here is a snippet of protractor.conf.js 
The modifySuiteName is where I change the location in the describe to path for sonar
describe('src.test.e2e.spec1.js', function() {...}

 framework: 'jasmine2',
  onPrepare: function() {
    var jasmineReporters = require('jasmine-reporters');
    jasmine.getEnv().addReporter(new jasmineReporters.SonarXmlReporter({
      consolidateAll: true,
      savePath: 'target/js',
      filePrefix: 'protractor',
      modifySuiteName: function(nextPath) {
        var pathSplit = nextPath.split('.');
        var path = ''
        if (pathSplit.length > 2) {
            for (i = 0; i < pathSplit.length - 2; i++) {
                path = path +  pathSplit[i] + "/"
            }
            path = path + pathSplit[pathSplit.length - 2] + "." + pathSplit[pathSplit.length - 1]
        } else {
            path = nextPath
        }
        return path
      }
    }

This is used in a maven build with entries in pom
        <sonar.tests>src/test/javascript,src/test/e2e,src/test/java</sonar.tests>
   <sonar.genericcoverage.unitTestReportPaths>target/js/protractor.xml,target/js/TESTS.xml</sonar.genericcoverage.unitTestReportPaths>

**Comment by gontard** [comment]
I use this branch in my project it works as expected. Thanks @PloughingAByteField

**Comment by miguelrincon** [comment]
@PloughingAByteField This PR is really cool and hasn't been merged in over a year, are you inclined to roll this one out as a standalone reporter project? Probably Sonar/Protractor is too niche for `jasmine-reporters`.

**Comment by PloughingAByteField** [comment]
It possibly should be standalone, particularly as sonarqube have changed so much around integration tests in 6.x. Unfort

**Comment by mmajcica** [comment]
It would have been a really handy thing to have this also this reporter. Not much has changed on SonarQube side since then...

**Pull request closed without merging**
