### PR TITLE
Change suite name for teamcity reporter

### PR DESCRIPTION
**Pull request by tarasok**
Added possibility to change suite name for teamcity reporter

### CODE REVIEW

**Comment by tarasok** [comment]
@larrymyers, could you please review and merge my request? It's really important to have feature to customize suite name, especially when running tests in different browsers.

**Comment by larrymyers** [comment]
@tarasok Please add additional test coverage for this change to the teamcity reporter so there is some documentation on how your change impacts the public interface to this reporter.

**Comment by tarasok** [comment]
sure, will add

**Comment by bloveridge** [comment]
Fixed some bugs, added tests.

**Pull request merged**
