### PR TITLE
Allow to modify the report filename for junit

### PR DESCRIPTION
**Pull request by magmax**
I've created the `modifyReportFilename` delegate, what allows to change the report file name for each report.

### CODE REVIEW

**Comment by rklaren** [comment]
@magmax thanks for making this, this would be the last bit needed to run protractor tests in paralllel with multi capabilities.

**Comment by magmax** [comment]
well, @rklaren, I'd like to see it in Master, because I requested the pull almost a month ago...

**Comment by anthonyjoubert** [comment]
I need this so much right now... Running the tests in parallel with protractor is way faster.

**Comment by bloveridge** [comment]
I'm looking at PRs tonight, hoping to get as many merged as possible. I've been really unresponsive the last few months and let them queued up to the point where I was too daunted to bother... trying to get that fixed.

**Comment by rklaren** [comment]
@bloveridge Thanks!

**Pull request merged**
