### PR TITLE
Add support for skipped reasons in JUnit XML

### LINKED ISSUE #123: Include reason in skipped test output
Jasmine tests that are skipped with a reason (http://stackoverflow.com/questions/31688650/is-it-possible-to-send-a-reason-for-jasmine-2-specs-skipped-with-xit-or-pending) do not include the reason in the junit reporter.

I'd like to include the reason in the report such that it can be visible from the build server.

### PR DESCRIPTION
**Pull request by scriby**
Followed the example on https://issues.jenkins-ci.org/browse/JENKINS-8713. It's working on my Jenkins server.

This should resolve #123.

### CODE REVIEW

**Comment by bloveridge** [comment]
Excellent, thanks for the PR. Please tidy up the indent levels to match the surrounding code (4 spaces) and we'll get this merged in.

**Comment by mindywhitsitt** [comment]
This would be useful to us. Now that the spacing has been fixed up, can this be merged in? Thanks!

**Comment by bloveridge** [comment]
Yep, sorry for the delay! Either I didn't receive or somehow overlooked the notification that the spacing had been fixed up. Merging and will tag a new release soon.

**Comment by mindywhitsitt** [comment]
Awesome. Thanks!

**Comment by bloveridge** [comment]
Published to npm as 2.0.8.

**Pull request merged**
